import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from lib import *
def rp(n): return "Rp " + f"{n:,}".replace(",",".")
with sync_playwright() as p:
    b=p.chromium.launch(**BROWSER)
    ctx=b.new_context(viewport={"width":1400,"height":900}, storage_state=OUT+"/state.json"); pg=ctx.new_page(); attach(pg)
    pg.goto(BASE); pg.wait_for_timeout(1000)
    today=pg.evaluate("new Date().toISOString().slice(0,10)"); print("today", today)
    # master extra checks
    nav(pg,"Kelas")
    pg.get_by_role("button", name="Tambah kelas").click(); m=modal(pg); m.locator("input").first.fill("kelas a"); m.get_by_role("button",name="Simpan").click(); toast(pg,"sudah ada"); m.get_by_role("button",name="Batal").click()
    pg.locator("table.ledger tbody tr", has_text="Kelas A").locator('button[title=Hapus]').click(); modal(pg).get_by_role("button",name="Hapus").click(); toast(pg,"masih dipakai")
    nav(pg,"Kategori kas")
    pg.locator("table.ledger tbody tr", has_text="Gaji/Honor").locator('button[title=Hapus]').click(); modal(pg).get_by_role("button",name="Hapus").click(); toast(pg,"dipakai sistem")
    # ---- TAGIHAN massal
    nav(pg,"Tagihan santri")
    pg.get_by_role("button", name="Buat tagihan").first.click(); m=modal(pg); pg.wait_for_timeout(500)
    print("massal info:", m.locator(".bg-brand-50").inner_text())
    m.get_by_role("button", name=re.compile(r"Buat \d+ tagihan")).click(); toast(pg,"tagihan dibuat"); pg.wait_for_timeout(500)
    print("tagihan rows:", pg.locator("table.ledger tbody tr").count())
    pg.get_by_role("button", name="Buat tagihan").first.click(); m=modal(pg); pg.wait_for_timeout(500)
    print("massal ulang:", m.locator(".bg-brand-50").inner_text()); m.get_by_role("button",name="Batal").click()
    # single: LKS + Kegiatan for Ahmad
    for kw in ["LKS","Kegiatan"]:
        pg.get_by_role("button", name="Buat tagihan").first.click(); m=modal(pg)
        m.get_by_role("button", name="Satu santri").click()
        m.get_by_placeholder("Ketik nama atau ID santri…").fill("ahmad"); pg.keyboard.press("Enter")
        fld(m,"Jenis kewajiban").select_option(label=kw); pg.wait_for_timeout(400)
        m.get_by_role("button", name=re.compile(r"Buat 1 tagihan")).click(); toast(pg,"1 tagihan dibuat"); pg.wait_for_timeout(300)
    # single for Muhammad Rizki (Seragam) then delete it
    pg.get_by_role("button", name="Buat tagihan").first.click(); m=modal(pg); m.get_by_role("button", name="Satu santri").click()
    m.get_by_placeholder("Ketik nama atau ID santri…").fill("rizki"); pg.keyboard.press("Enter"); fld(m,"Jenis kewajiban").select_option(label="Seragam"); pg.wait_for_timeout(300)
    m.get_by_role("button", name=re.compile(r"Buat 1 tagihan")).click(); pg.wait_for_timeout(500)
    row=pg.locator("table.ledger tbody tr", has_text="Seragam"); row.locator('button[title=Hapus]').click(); modal(pg).get_by_role("button",name="Hapus").click(); toast(pg,"Tagihan dihapus")
    # edit nominal Umar syahriyah -> 40000
    row=pg.locator("table.ledger tbody tr", has_text="Umar Faruq"); row.locator('button[title="Ubah nominal"]').click(); m=modal(pg)
    fld(m,"Nominal").fill("40000"); m.get_by_role("button",name="Simpan").click(); toast(pg,"diperbarui"); pg.wait_for_timeout(300)
    print("umar row:", pg.locator("table.ledger tbody tr", has_text="Umar Faruq").inner_text().replace("\n"," | "))
    print("summary:", pg.locator("div.grid.grid-cols-2").first.inner_text().replace("\n"," | "))
    # ---- PEMBAYARAN Ahmad: syahriyah full + LKS partial
    nav(pg,"Terima pembayaran")
    pg.get_by_placeholder("Ketik nama atau ID santri…").fill("Ahmad"); pg.keyboard.press("Enter"); pg.wait_for_timeout(500)
    items=pg.locator("ul.divide-y li"); print("open tagihan ahmad:", items.count())
    items.filter(has_text="Syahriyah").locator("input[type=checkbox]").check()
    items.filter(has_text="LKS").locator("input[type=checkbox]").check()
    lks=items.filter(has_text="LKS").locator("input[inputmode=numeric]")
    lks.fill("99999"); pg.wait_for_timeout(100)
    print("over disabled:", pg.get_by_role("button",name="Simpan pembayaran").is_disabled(), pg.locator("text=Melebihi sisa").count())
    lks.fill("10000")
    print("total:", pg.locator("p.text-3xl").inner_text())
    pg.get_by_role("button",name="Simpan pembayaran").click(); toast(pg,"Pembayaran disimpan")
    with ctx.expect_page() as np: pg.get_by_role("button",name="Cetak kwitansi").click()
    kw=np.value; attach(kw,"kwitansi"); kw.wait_for_timeout(1200)
    print("KWITANSI:", kw.locator("article").inner_text().replace("\n"," | ")[:600]); kw.screenshot(path=OUT+"/kwitansi.png"); kw.close()
    pg.get_by_role("button",name="Pembayaran berikutnya").click(); pg.wait_for_timeout(1500)
    # Aisyah cicilan 20000 then 30000
    for amt in ["20000","30000"]:
        pg.get_by_placeholder("Ketik nama atau ID santri…").fill("Aisyah"); pg.keyboard.press("Enter"); pg.wait_for_timeout(400)
        expect(pg.locator("ul.divide-y li").filter(has_text="Syahriyah")).to_be_visible()
        it=pg.locator("ul.divide-y li").filter(has_text="Syahriyah"); it.locator("input[type=checkbox]").check()
        it.locator("input[inputmode=numeric]").fill(amt); pg.get_by_role("button",name="Simpan pembayaran").click(); toast(pg,"Pembayaran disimpan")
        pg.get_by_role("button",name="Pembayaran berikutnya").click(); pg.wait_for_timeout(300)
    pg.get_by_placeholder("Ketik nama atau ID santri…").fill("Aisyah"); pg.keyboard.press("Enter"); pg.wait_for_timeout(400)
    print("aisyah after 2 cicilan:", pg.locator("text=Semua tagihan sudah lunas").count())
    # Rizki full via query param from tagihan page
    pg.goto(BASE+"/tagihan"); pg.wait_for_timeout(600)
    pg.locator("table.ledger tbody tr", has_text="Muhammad Rizki").locator('a[title="Terima pembayaran"]').click(); pg.wait_for_timeout(600)
    pg.get_by_role("button",name="Pilih semua").count() and pg.get_by_role("button",name="Pilih semua").click()
    if pg.locator("ul.divide-y li input[type=checkbox]").count()==1: pg.locator("ul.divide-y li input[type=checkbox]").check()
    pg.get_by_role("button",name="Simpan pembayaran").click(); toast(pg,"Pembayaran disimpan")
    # riwayat & batal
    pg.get_by_role("button",name="Pembayaran berikutnya").click()
    pg.get_by_role("button",name="Riwayat").click(); pg.wait_for_timeout(500)
    rr=pg.locator("table.ledger tbody tr"); print("riwayat rows:", rr.count(), "| tfoot:", pg.locator("tfoot").inner_text().replace("\n"," "))
    rr.filter(has_text="Muhammad Rizki").locator('button[title=Hapus]').click(); modal(pg).get_by_role("button",name="Hapus pembayaran").click(); toast(pg,"Pembayaran dihapus"); pg.wait_for_timeout(400)
    d=fs(pg)['db']
    rz=[t for t in d['tagihan'].values() if t['santriNama']=='Muhammad Rizki']
    print("rizki tagihan after batal:", [(t['kewajibanNama'],t['dibayar'],t['sisa'],t['status']) for t in rz])
    print("kas count:", len(d['kas']), "pembayaran:", len(d['pembayaran']))
    print("tagihan statuses:", sorted((t['santriNama'][:6],t['kewajibanNama'][:8],t['dibayar'],t['sisa'],t['status']) for t in d['tagihan'].values()))
    # ---- GAJI
    nav(pg,"Gaji & honor")
    pg.get_by_role("button",name="Buat slip gaji").first.click(); m=modal(pg)
    fld(m,"Ustadz / ustadzah").select_option(label="Ahmad Syauqi — Kepala TPQ"); pg.wait_for_timeout(300)
    print("default komponen:", m.locator(".divide-y > div").all_inner_texts())
    m.locator("select").filter(has_text="+ Tambah komponen").select_option(label="Potongan (Potongan)")
    m.locator(".divide-y > div").filter(has_text="Potongan").locator("input").fill("50000")
    print("slip totals:", m.locator("dl").inner_text().replace("\n"," "))
    m.get_by_role("button",name="Simpan slip").click(); toast(pg,"Slip gaji disimpan"); pg.wait_for_timeout(400)
    pg.get_by_role("button",name="Buat slip gaji").first.click(); m=modal(pg)
    fld(m,"Ustadz / ustadzah").select_option(label="Fatimah Az-Zahra"); pg.wait_for_timeout(200)
    m.get_by_role("button",name="Simpan slip").click(); pg.wait_for_timeout(400)
    pg.get_by_role("button",name="Buat slip gaji").first.click(); m=modal(pg); fld(m,"Ustadz / ustadzah").select_option(label="Fatimah Az-Zahra"); pg.wait_for_timeout(200)
    print("dobel warning:", m.locator("text=Sudah ada slip").count()); m.get_by_role("button",name="Batal").click()
    print("gaji rows:", pg.locator("table.ledger tbody tr").count())
    with ctx.expect_page() as np: pg.locator("table.ledger tbody tr", has_text="Ahmad Syauqi").locator('button[title="Cetak slip"]').click()
    sl=np.value; attach(sl,"slip"); sl.wait_for_timeout(1000); print("SLIP:", sl.locator("article").inner_text().replace("\n"," | ")[:400]); sl.screenshot(path=OUT+"/slip.png"); sl.close()
    pg.locator("table.ledger tbody tr", has_text="Fatimah").locator('button[title=Hapus]').click(); modal(pg).get_by_role("button",name="Hapus slip").click(); toast(pg,"Slip gaji dihapus")
    # ---- PENGELUARAN / PEMASUKAN
    nav(pg,"Pengeluaran")
    pg.get_by_role("button",name="Catat pengeluaran").first.click(); m=modal(pg)
    fld(m,"Kategori").select_option("ATK"); fld(m,"Keterangan").fill("Kertas HVS"); fld(m,"Nominal").fill("250000"); m.get_by_role("button",name="Simpan").click(); toast(pg,"disimpan")
    print("kategori opsi has Gaji?", "Gaji/Honor" in fld(pg.locator("main"),"Kategori").inner_text())
    pg.locator("table.ledger tbody tr", has_text="Kertas").locator('button[title=Ubah]').click(); m=modal(pg); fld(m,"Nominal").fill("300000"); m.get_by_role("button",name="Simpan").click(); pg.wait_for_timeout(400)
    print("pengeluaran row:", pg.locator("table.ledger tbody tr").first.inner_text().replace("\n"," | "))
    pg.get_by_role("button",name="Catat pengeluaran").first.click(); m=modal(pg); fld(m,"Kategori").select_option("Listrik"); fld(m,"Nominal").fill("150000"); m.get_by_role("button",name="Simpan").click(); pg.wait_for_timeout(300)
    pg.locator("table.ledger tbody tr", has_text="Listrik").locator('button[title=Hapus]').click(); modal(pg).get_by_role("button",name="Hapus").click(); toast(pg,"dihapus")
    pg.get_by_role("button",name="Catat pengeluaran").first.click(); m=modal(pg); fld(m,"Kategori").select_option("Air"); m.get_by_role("button",name="Simpan").click(); toast(pg,"lebih dari 0"); m.get_by_role("button",name="Batal").click()
    nav(pg,"Pemasukan lain")
    pg.get_by_role("button",name="Catat pemasukan lain").first.click(); m=modal(pg); fld(m,"Kategori").select_option("Donasi"); fld(m,"Nominal").fill("500000"); m.get_by_role("button",name="Simpan").click(); toast(pg,"disimpan")
    # ---- PENGATURAN saldo awal
    nav(pg,"Pengaturan")
    fld(pg.locator("main"),"Saldo awal").fill("2000000"); fld(pg.locator("main"),"Kota").fill("Bekasi")
    pg.get_by_placeholder("Contoh: QRIS").fill("QRIS"); pg.get_by_role("button",name="Tambah",exact=True).click()
    pg.get_by_role("button",name="Simpan pengaturan").click(); toast(pg,"Pengaturan disimpan"); pg.wait_for_timeout(400)
    # ---- BUKU KAS
    nav(pg,"Buku kas"); pg.wait_for_timeout(800)
    print("BUKU KAS stats:", pg.locator("div.grid.grid-cols-2").first.inner_text().replace("\n"," | "))
    print("buku rows:", pg.locator("table.ledger tbody tr").count(), "| foot:", pg.locator("tfoot").inner_text().replace("\n"," "))
    # ---- DASHBOARD
    nav(pg,"Dashboard"); pg.wait_for_timeout(1000)
    print("DASH hero:", pg.locator("section").first.inner_text().replace("\n"," | "))
    print("DASH tagihan:", pg.locator("section").nth(1).inner_text().replace("\n"," | ")[:300])
    pg.screenshot(path=OUT+"/dash.png", full_page=True)
    # ---- LAPORAN
    nav(pg,"Laporan keuangan"); pg.wait_for_timeout(800); print("LAPKEU:", pg.locator("main").inner_text().replace("\n"," | ")[:700])
    nav(pg,"Tunggakan"); pg.wait_for_timeout(600); print("TUNGGAKAN:", pg.locator("table.ledger tbody").inner_text().replace("\n"," | ")[:500])
    nav(pg,"Kartu santri"); pg.get_by_placeholder("Ketik nama atau ID santri…").fill("ahmad"); pg.keyboard.press("Enter"); pg.wait_for_timeout(600)
    print("KARTU:", pg.locator("main").inner_text().replace("\n"," | ")[:600])
    # ---- PENGGUNA
    nav(pg,"Pengguna")
    pg.get_by_role("button",name="Tambah pengguna").click(); m=modal(pg)
    fld(m,"Nama").fill("Bendahara Satu"); fld(m,"Email").fill("bend@tpq.id"); fld(m,"Kata sandi awal").fill("rahasia2")
    m.get_by_role("button",name="Tambah pengguna").click(); toast(pg,"Pengguna ditambahkan"); pg.wait_for_timeout(400)
    print("users:", pg.locator("main ul").first.inner_text().replace("\n"," | "))
    print("still admin logged:", pg.locator("aside").inner_text().count("Siti Aminah"))
    ctx.storage_state(path=OUT+"/state2.json")
    print("ERRORS:", [e for e in errors if "403" not in e])
    b.close()
