import sys, os, json; sys.path.insert(0, os.path.dirname(__file__))
from lib import *
with sync_playwright() as p:
    b=p.chromium.launch(**BROWSER)
    ctx=b.new_context(viewport={"width":1400,"height":860}, storage_state=OUT+"/state2.json"); pg=ctx.new_page(); attach(pg)
    pg.goto(BASE); pg.wait_for_timeout(900)
    pg.locator('aside a[title="Akun saya"]').click(); pg.wait_for_timeout(400); print("url:", pg.url)
    main=pg.locator("main")
    fld(main,"Nama tampilan").fill("Siti Aminah, S.Pd"); pg.get_by_role("button",name="Simpan nama").click(); toast(pg,"Nama diperbarui"); pg.wait_for_timeout(300)
    print("sidebar name:", pg.locator("aside a[title='Akun saya'] p").first.inner_text())
    fld(main,"Kata sandi lama").fill("salah123"); fld(main,"Kata sandi baru").fill("baru123"); fld(main,"Ulangi kata sandi baru").fill("baru124")
    print("mismatch disabled:", pg.get_by_role("button",name="Ganti kata sandi").is_disabled(), main.locator("text=Tidak sama").count())
    fld(main,"Ulangi kata sandi baru").fill("baru123"); pg.get_by_role("button",name="Ganti kata sandi").click(); toast(pg,"Kata sandi lama salah")
    fld(main,"Kata sandi lama").fill("rahasia1"); pg.get_by_role("button",name="Ganti kata sandi").click(); toast(pg,"berhasil diganti"); pg.wait_for_timeout(300)
    print("fields cleared:", fld(main,"Kata sandi lama").input_value()=="")
    main.locator("button[aria-label='Tampilkan kata sandi']").first.click(); print("toggle type:", fld(main,"Kata sandi lama").get_attribute("type"))
    # logout + login with new pw
    pg.locator('button[title=Keluar]').click(); pg.wait_for_timeout(400)
    pg.get_by_label("Email").fill("admin@tpq.id"); pg.get_by_label("Kata sandi").fill("rahasia1"); pg.get_by_role("button",name="Masuk").click(); pg.wait_for_timeout(400)
    print("old pw:", pg.locator("p.text-rose-ink").inner_text())
    pg.get_by_label("Kata sandi").fill("baru123"); pg.get_by_role("button",name="Masuk").click(); pg.wait_for_timeout(1000)
    print("logged in:", pg.locator("aside").count())
    # admin atur login - API missing in dev
    pg.goto(BASE+"/pengguna"); pg.wait_for_timeout(500)
    row=pg.locator("table.ledger tbody tr", has_text="Bendahara Satu")
    row.get_by_role("button", name="Atur login").click(); m=modal(pg)
    print("save disabled w/o change:", m.get_by_role("button",name="Simpan").is_disabled())
    fld(m,"Kata sandi baru").fill("123"); print("short disabled:", m.get_by_role("button",name="Simpan").is_disabled())
    fld(m,"Kata sandi baru").fill("bendahara9"); m.get_by_role("button",name="Simpan").click(); toast(pg,"Fungsi server belum tersedia")
    # stub API success
    got=[]
    pg.route("**/api/admin-user", lambda r: (got.append((r.request.headers.get("authorization","")[:7], r.request.post_data)), r.fulfill(status=200, content_type="application/json", body='{"ok":true}')))
    m.get_by_role("button",name="Simpan").click(); toast(pg,"Login pengguna diperbarui")
    print("api called:", got)
    row.get_by_role("button", name="Atur login").click(); m=modal(pg); fld(m,"Email login").fill("dup@x.id")
    pg.unroute("**/api/admin-user"); pg.route("**/api/admin-user", lambda r: r.fulfill(status=409, content_type="application/json", body=json.dumps({"error":"Email ini sudah dipakai akun lain."})))
    m.get_by_role("button",name="Simpan").click(); toast(pg,"sudah dipakai")
    pg.screenshot(path=OUT+"/pengguna.png")
    print("ERRORS:", errors); b.close()
